version: '3.8'

services:
  ollama:
    image: devaraj13/ollama:latest
    container_name: ollama
    ports:
      - "11435:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 10s
      retries: 3

  qdrant:
    image: devaraj13/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT__SERVICE__HTTP_PORT=6333
      - QDRANT__SERVICE__GRPC_PORT=6334
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  rag-api:
    image: devaraj13/rag-api:latest
    container_name: rag-api
    ports:
      - "9000:9000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6334
      - EMBED_MODEL=nomic-embed-text
      - GENERATE_MODEL=llama3.1:8b
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
      - EMBED_BATCH=10
      - UPSERT_BATCH=100
    depends_on:
      ollama:
        condition: service_healthy
      qdrant:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  ui:
    image: devaraj13/rag-ui:latest
    container_name: rag-ui
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - MODEL_NAME=llama3.1:8b
      - FALLBACK_MODEL=llama3.1:8b
      - RAG_API_URL=http://rag-api:9000
    depends_on:
      rag-api:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  ollama_data:
    driver: local
  qdrant_data:
    driver: local

networks:
  default:
    name: rag-network
